services:
  - type: web
    name: fillinfo
    env: node
    nodeVersion: 20
    buildCommand: npm install && CI=false npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
